## 一个线程出现OOM会影响其他线程吗

### 引言

这题是一个网友@大脸猫爱吃鱼给我的提问，出自今年校招美团三面的一个真题。大致如下

>  一个进程有3个线程，如果一个线程抛出oom，其他两个线程还能运行么?

先说一下答案，答案是**还能运行**。不瞒大家说，真在面试中，我遇到这一题，我估计也是答错。因为我初看到这一题，内心嘿嘿一笑，觉得这题是在考察JVM的内存结构。我第一反应是OOM的常见情况**堆溢出**，也就是下面的这种异常

```java
java.lang.OutOfMemoryError: Java heap space
```

先回忆一下，多线程中栈与堆是公有的还是私有的？回答如下

**在多线程环境下，每个线程拥有一个栈和一个程序计数器。栈和程序计数器用来保存线程的执行历史和线程的执行状态，是线程私有的资源。其他的资源（比如堆、地址空间、全局变量）是由同一个进程内的多个线程共享。**

也就是说，堆是线程共享。那么一个线程堆抛出OOM异常，我第一反应是另外两个线程也抛出OOM异常，毕竟堆是共有的，大家应该都抛出异常。于是，我机智的让@大脸猫爱吃鱼写个代码去测试一下，结果我被啪啪啪打脸了。测试代码伪如下

一个线程去构造堆溢出，每隔1秒申请一次堆，代码长下面这样

```java
new Thread(() -> {
	List<byte[]> list=new ArrayList<byte[]>();
	while(true){
		System.out.println(new Date().toString()+Thread.currentThread()+"==");
		byte[] b = new byte[1024*1024*1];
		list.add(b);
    try {
			Thread.sleep(1000);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}).start();
```

另一个线程，睡眠1秒然后输出就好，代码长下面这样

```java
new Thread(() -> {
	while(true){
		System.out.println(new Date().toString()+Thread.currentThread()+"==");
		try {
			Thread.sleep(1000);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}).start();
```

结果，输出是长下面这样的

![img](https://note.youdao.com/yws/public/resource/56347de0c9d0b624bcbb02366ca7a2b8/xmlnote/wcp1587736280936712/D94BC14E475B4B548D9DD9582D431131/24643)

大家发现了么，一个线程溢出了，其他线程还在跑，这好像和我们的认知不大一样。坦白说，我看到这个结果，瞬间觉得自己一世英名毁于一旦，从此无法抬起头来做人。没办法了，只能亮出工具来看一下了。先说一下，在本例测试中，参数如下

```
-Xms16m -Xmx32m
-Xms 初始堆内存 
-Xmx 最大堆内存
```

### 分析

接下来，亮出JvisualVM看堆的变化，注意看上面那张图，抛出OOM的时间约在00:11:45 左右，因此我们需要重点关注00:11:45左右的曲线变化，如下图所示

![img](https://note.youdao.com/yws/public/resource/56347de0c9d0b624bcbb02366ca7a2b8/xmlnote/wcp1587736280936712/B097A354E56B48E989D05A5802F485F1/24648)

如图所示，我们仔细观察一下在00:11:44~00:11:45之间曲线变化，你会发现使用堆的数量，突然间急剧下滑！这代表着一点，**当一个线程抛出OOM异常后，它所占据的内存资源会全部被释放掉，从而不会影响其他线程的运行！**

讲到这里大家应该懂了，此题的答案为**一个线程溢出后，进程里的其他线程还能照常运行。**注意了，这个例子我只演示了堆溢出的情况。**如果是栈溢出，结论也是一样的，大家可自行通过代码测试**。

说时迟，那时快。一个机智的网友又给我提了一个问题?

**如果主线程抛异常退出了，子线程还能运行么？**

ok，这个问题要从子线程和主线程的关系讲起。先来一个定义：

> **线程不像进程，一个进程中的线程之间是没有父子之分的，都是平级关系。即线程都是一样的, 退出了一个不会影响另外一个。**

因此，答案是**如果主线程抛异常退出了，子线程还能运行。**

但是有一个例外情况，如果这些子线程都是**守护线程**，那么子线程会随着主线程结束而结束。

### 总结

- **当一个线程抛出OOM异常（或者是栈溢出）后，它所占据的内存资源会全部被释放掉，从而不会影响其他线程的运行！**
- **一个进程之间的线程没有父子之分，都是平级，所以一个线程退出不会影响另外一个。但有一个例外是子线程是守护线程。**

## 条件变量的虚假唤醒

### 引言

条件变量是我们常用的同步原语之一，它的正确使用方式一般如下图：

![img](https://note.youdao.com/yws/public/resource/56347de0c9d0b624bcbb02366ca7a2b8/xmlnote/wcp1583142865172718/6E215F69E86F4FAC9E350773C7905901/21040)

在wait端，我们必须把判断布尔条件和wait()放到while循环中，而不能用if语句，原因是可能会引起**虚假唤醒**。那么，究竟什么是虚假唤醒，导致虚假唤醒的原因又是什么呢？

### 什么是虚假唤醒？

举个例子，我们现在有一个生产者-消费者队列和三个线程。

1. 1号线程从队列中获取了一个元素，此时队列变为空。

2. 2号线程也想从队列中获取一个元素，但此时队列为空，2号线程便只能进入阻塞(cond.wait())，等待队列非空。

3. 这时，3号线程将一个元素入队，并调用cond.notify()唤醒条件变量。

4. 处于等待状态的2号线程接收到3号线程的唤醒信号，便准备解除阻塞状态，执行接下来的任务(获取队列中的元素)。

5. 然而可能出现这样的情况：当2号线程准备获得队列的锁，去获取队列中的元素时，此时1号线程刚好执行完之前的元素操作，返回再去请求队列中的元素，1号线程便获得队列的锁，检查到队列非空，就获取到了3号线程刚刚入队的元素，然后释放队列锁。

6. 等到2号线程获得队列锁，判断发现队列仍为空，1号线程“偷走了”这个元素，所以对于2号线程而言，这次唤醒就是“虚假”的，它需要再次等待队列非空。

### 使用while()判断的原因

在多核处理器下，pthread_cond_signal可能会激活多于一个线程（阻塞在条件变量上的线程）。结果就是，当一个线程调用`pthread_cond_signal()`后，多个调用`pthread_cond_wait()`或`pthread_cond_timedwait()`的线程返回。这种效应就称为“虚假唤醒”。Linux man page中也有提到：

虚假唤醒造成的后果：

> If a signal is delivered to a thread waiting for a condition variable, upon return from the signal handler the thread resumes waiting for the condition variables as if it was not interrupted, or it shall return zero due to spurious wakeup.

需要对条件进行再判断以避免虚假唤醒:

![img](https://note.youdao.com/yws/public/resource/56347de0c9d0b624bcbb02366ca7a2b8/xmlnote/wcp1583142865172718/8CE034FC884240D7BFAB6E24B723C8D2/21044)

如果用if判断，多个等待线程在满足if条件时都会被唤醒(虚假的)，但实际上条件并不满足，生产者生产出来的消费品已经被第一个线程消费了。

这就是我们使用while去做判断而不是使用if的原因：**因为等待在条件变量上的线程被唤醒有可能不是因为条件满足而是由于虚假唤醒**。所以，我们需要对条件变量的状态进行不断检查直到其满足条件，不仅要在`pthread_cond_wait()`前检查条件是否成立，在`pthread_cond_wait()`之后也要检查。

## execute()和submit()区别

### 可以接受的任务类型

**submit：**

![img](https://note.youdao.com/yws/public/resource/56347de0c9d0b624bcbb02366ca7a2b8/xmlnote/wcp1588060098734947/82FDA34B084A42F8A1EC18F959694660/25172)

**execute：**

![img](https://note.youdao.com/yws/public/resource/56347de0c9d0b624bcbb02366ca7a2b8/xmlnote/wcp1588060098734947/832ECE58DF59414C86F4AA0CCAC4B733/25173)

可以看出：

- execute只能接受Runnable类型的任务

- submit不管是Runnable还是Callable类型的任务都可以接受，但是Runnable返回值均为void，所以使用Future的get()获得的还是null

### 返回值

由Callable和Runnable的区别可知：

- execute没有返回值

- submit有返回值，所以需要返回值的时候必须使用submit

### 异常

**1.execute中抛出异常**

​                    execute中的是Runnable接口的实现，所以只能使用try、catch来捕获CheckedException，通过实现UncaughtExceptionHande接口处理UncheckedException

​                    即和普通线程的处理方式完全一致

**2.submit中抛出异常**

**不管提交的是Runnable还是Callable类型的任务，如果不对返回值Future调用get()方法，都会吃掉异常**

​                   先来看下Callable定义

1. public interface Callable<V> {
2. V call() throws Exception;
3. }

**其中的call能够抛出Exception异常，所以不管是CheckedException还是UncheckedException，直接抛出即可**

1. import java.util.concurrent.Callable;
2. import java.util.concurrent.ExecutionException;
3. import java.util.concurrent.ExecutorService;
4. import java.util.concurrent.Executors;
5. import java.util.concurrent.Future;
6. public class ThreadExceptionTest {
7. public static void main(String[] args) {
8. ExecutorService executor = Executors.newCachedThreadPool();
9. Future<Boolean> future = executor.submit(new CallableTask());
10. try {
11. future.get();
12. } catch (InterruptedException e) {
13. e.printStackTrace();
14. } catch (ExecutionException e) {
15. e.printStackTrace();
16. }
17. executor.shutdown();//必须不能忘，否则会一致卡在那里
18. }
19. }

1. class CallableTask implements Callable<Boolean>{
2. public Boolean call() throws Exception {
3. // InputStream in = new FileInputStream(new File("xx.pdf"));
4. int num = 3/0;
5. return false;
6. }
7. }

结果为：

```java
java.util.concurrent.ExecutionException: java.lang.ArithmeticException: / by zero
at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
at java.util.concurrent.FutureTask.get(FutureTask.java:83)
at my.ThreadExceptionTest.main(ThreadExceptionTest.java:21)
  
Caused by: java.lang.ArithmeticException: / by zero
at my.CallableTask.call(ThreadExceptionTest.java:57)
at my.CallableTask.call(ThreadExceptionTest.java:1)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:619)
```

## Thread.sleep()与CPU之间的关系

我们可能经常会用到 Thread.Sleep 函数来使线程挂起一段时间。那么你有没有正确的理解这个函数的用法呢？思考下面这两个问题：

- 假设现在是 2008-4-7 12:00:00.000，如果我调用一下 Thread.Sleep(1000) ，在 2008-4-7 12:00:01.000 的时候，这个线程会 不会被唤醒？
- 某人的代码中用了一句看似莫明其妙的话：Thread.Sleep(0) 。既然是 Sleep 0 毫秒，那么他跟去掉这句代码相比，有啥区别么？

<hr>


我们先回顾一下操作系统原理。操作系统中，CPU竞争有很多种策略。Unix系统使用的是**时间片算法**，而Windows则属于**抢占式的**。在抢占式操作系统中，假设有若干进程，操作系统会根据他们的优先级、饥饿时间（已经多长时间没有使用过 CPU 了），给他们算出一 个总的优先级来。操作系统就会把 CPU 交给总优先级最高的这个进程。**当进程执行完毕或者自己主动挂起后，操作系统就会重新计算一 次所有进程的总优先级，然后再挑一个优先级最高的把 CPU 控制权交给它**。

**Sleep函数就是干这事的，他告诉操作系统“在未来的多少毫秒内我不参与CPU竞争”。**

> sleep==> 将当前线程挂起指定的时间

看完了 Thread.Sleep 的作用，我们再来想想文章开头的两个问题。

- 对于第一个问题，答案是：不一定。因为你只是告诉操作系统：在未来的1000毫秒内我不想再参与到CPU竞争。那么1000毫秒过去之后，这时候也许另外一个线程正在使用CPU，那么这时候操作系统是不会重新分配CPU的，直到那个线程挂起或结束；况且，即使这个时候恰巧轮到操作系统进行CPU 分配，**那么当前线程也不一定就是总优先级最高的那个**，CPU还是可能被其他线程抢占去。

- 与此相似的，Thread有个Resume函数，是用来唤醒挂起的线程的。好像上面所说的一样，这个函数只是“**告诉操作系统我从现在起开始参与CPU竞争了**”，这个函数的调用并不能马上使得这个线程获得CPU控制权。



- 7号mm就换了个说法：“在未来的0毫秒之内不要再叫我上来吃蛋糕了”。这个指令操作系统是接受的，**于是此时操作系统就会重新计算大家的总优先级——注意这个时候是连7号一起计算的，因为“0毫秒已经过去了”嘛。**因此如果没有比7号更需要吃蛋糕的人出现，那么下一次7号还是会被叫上来吃蛋糕。

因此，Thread.Sleep(0)的作用，**就是“触发操作系统立刻重新进行一次CPU竞争”。竞争的结果也许是当前线程仍然获得CPU控制权，也许会换成别的线程获得CPU控制权**。这也是我们在大循环里面经常会写一句Thread.Sleep(0) ，因为这样就给了其他线程比如Paint线程获得CPU控制权的权力，**这样界面就不会假死在那里**。

末了说明一下，虽然上面提到说“除非它自己放弃使用 CPU ，否则将完全霸占 CPU”，但这个行为仍然是受到制约的——**操作系统会监控你霸占CPU的情况，如果发现某个线程长时间霸占CPU，会强制使这个线程挂起**。因此在实际上不会出现“一个线程一直霸占着 CPU 不放”的情况。至于我们的大循环造成程序假死，并不是因为这个线程一直在霸占着CPU。**实际上在这段时间操作系统已经进行过多次CPU竞争了，只不过其他线程在获得CPU控制权之后很短时间内马上就退出了，于是就又轮到了这个线程继续执行循环，于是就又用了很久才被操作系统强制挂起，因此反应到界面上，看起来就好像这个线程一直在霸占着CPU一样**。